[window]

opacity = 0.80
padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "BlexMono NF"
bold.family = "BlexMono NF"
italic.family = "BlexMono NF"
bold_italic.family = "BlexMono NF"

# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'
