#!/bin/sh
# Make sure you have virtualbox installed on your system, also make sure that you have
# the right vbox kernel module and the latest linux kernel/headers
start_vm(){
vms=$(vboxmanage list vms | awk -F\" '{print $2}')
choice=$(printf "%s\n" "$vms" | dmenu -i -p "Start virtual machine: ")

if [ -z "$choice" ]; then
    printf "%s\n" "Nothing chosen, exiting..."
    exit 1
else
    (vboxmanage startvm "$choice" && notify-send "Starting $choice") || \
        notify-send "Exiting command" "No such VM found"
fi
}

shutdown_vm(){
    # Check if some vms are running
if [ -z "$(vboxmanage list runningvms)" ]; then
    notify-send "No running vms" ; exit 0
else 
    running_vms=$(vboxmanage list runningvms | awk -F\" '{print $2}')
    choice=$(printf "%s\n" "$running_vms" | dmenu -i -p "Shutdown virtual machine: " )
    (vboxmanage controlvm "$choice" acpipowerbutton ; notify-send "Shutting down $choice") || \
        notify-send "Exiting command" "No running VM found"
fi
}

# Main
action=$(printf "Start VM\nShutdown VM"| dmenu -i -p "Select action: ")
case "$action" in
    "Start VM") start_vm ;;
    "Shutdown VM") shutdown_vm ;;
    *) exit 1 ;;
esac
