#!/bin/bash
# Script to change terminal, vim and wallpaper colorscheme
# Make sure the themes located in ~/.config/alacritty/colors & ~/.config/vim/colors are there
# Also make sure to install 'alacritty-colorschemes' via pip
# https://pypi.org/project/alacritty-colorscheme/
# NOTES: the name of the vim theme and alacritty theme must be the same for this script to work, this script only works with alacritty

# Please change the variables to your liking
day="base16-tomorrow.yml"
night="base16-tomorrow-night.yml"

declare -a options=(
    "Day"
    "Night" 
    "Manual"
)

chosen_col_scheme=$(printf '%s\n' "${options[@]}" | dmenu -i -p 'Please Select Colorscheme: ' "${@}")

day_scheme(){
    if [ -n "$(alacritty-colorscheme -V apply $day)" ]; then 
        notify-send "Failed to apply day colorscheme" "Please check the spelling or if the theme exists..." 
        exit 0 
    else
        notify-send "Day colorscheme"
        exit 0
    fi
}

night_scheme() {
    if [ -n "$(alacritty-colorscheme -V apply $night)" ]; then
        notify-send "Failed to apply night colorscheme" "Please check the spelling or if the theme exists..." 
        exit 0
    else 
        notify-send "Night colorscheme"
        exit 0
    fi
}

manual_scheme(){
    manual_theme=$(printf '%s\n' "$(alacritty-colorscheme list)" | dmenu -i -l 15 -p 'Theme to apply: ' "${@}")
    [ -z "$manual_theme" ] &&  exit 0
    if [ -z "$(alacritty-colorscheme -V apply "$manual_theme")" ]; then
        notify-send "Manual colorscheme" "Applied $manual_theme" 
        exit 0
    else 
        notify-send "Colorscheme not found" "Please try again, check your spelling..."
        exit 0
    fi
}

case $chosen_col_scheme in
    "Day") day_scheme;;
    "Night") night_scheme;;
    "Manual") manual_scheme ;; 
    *) exit 0 ;;
esac
